//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Gestión.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialBusqueda
    {
        public int id { get; set; }
        public string usuarioId { get; set; }
        public string nombre { get; set; }
        public string consulta { get; set; }
        public string categoria { get; set; }
        public string tipoPrecio { get; set; }
        public Nullable<System.DateTime> fechaBusqueda { get; set; }
    }
}
