//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Gestión.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class ProyectoBusquedaEntities : DbContext
    {
        public ProyectoBusquedaEntities()
            : base("name=ProyectoBusquedaEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        // Adaptar el método para aceptar los nuevos parámetros
        public virtual ObjectResult<buscarPorNombre_Result> buscarPorNombre(string consulta, Nullable<int> cantidad, string tipo = null, string tipo_precio = null)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));

            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));

            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));

            var tipo_precioParameter = tipo_precio != null ?
                new ObjectParameter("tipo_precio", tipo_precio) :
                new ObjectParameter("tipo_precio", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPorNombre_Result>("buscarPorNombre", consultaParameter, cantidadParameter, tipoParameter, tipo_precioParameter);
        }
    }
}
